[package]
name = "dropbear_unlock_console"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
ssh2 = "0.9"
rpassword = "7.0"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
